![alt tag](https://codelearn.io/Upload/Blog/thu-vien-numpy-trong-python-63724882299.0039.png)

# **What is Numpy?**
**NumPy** là thư viện cơ bản cho tính toán khoa học bằng Python. Nó là một thư viện Python cung cấp một đối tượng mảng đa chiều, các đối tượng dẫn xuất khác nhau (chẳng hạn như các mảng và ma trận có mặt nạ) và một loạt các quy trình cho các hoạt động nhanh trên mảng, bao gồm toán học, logic, thao tác hình dạng, sắp xếp, lựa chọn, I / O , các phép biến đổi Fourier rời rạc, đại số tuyến tính cơ bản, các phép toán thống kê cơ bản, mô phỏng ngẫu nhiên và hơn thế nữa.

# **Reference**
https://github.com/ageron/handson-ml2/blob/ce94de16f017f78b0991a3d3ae18b3de70b15118/tools_numpy.ipynb

# **Numpy: Import**
Import thư viện **numpy**. Hầu hết mọi người sử dụng nó dưới dạng **np**

In [47]:
import numpy as np

# **Numpy: Vocabulary**

- Trong **Numpy**, mỗi chiều được gọi là một **axis** (1 trục)
- Số lượng **axis** được gọi là **rank** (hạng)
 - Ví dụ: Ma trận 3x4 là mảng có **rank** = 2 vì nó có 2 chiều
    
        1 1 1 1
        2 3 4 5
        9 8 7 6
 - Trục (**axis**) thứ nhất có độ dài 3 (dòng), trục thứ hai có độ dài 4 (cột)
- Danh sách độ dài trục được gọi là **shape** của mảng
 - Ví dụ: **Shape** của ma trận trên là (3, 4)
- **size** của một mảng là tổng số phần tử, là tích của tất cả các độ dài trục (ví dụ: 3 * 4 = 12)

# **Numpy: Creating Arrays**

## **np.zeros**

Hàm **zeros** tạo một mảng chứa bất kì số lượng số 0 nào

In [48]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Tạo một mảng 2D (tức là một ma trận) bằng cách cung cấp một bộ dữ liệu với số lượng hàng và cột mong muốn. Ví dụ, đây là ma trận 3x4:

In [49]:
np.zeros((4, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [50]:
arr = np.zeros((5, 6))
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [51]:
arr.shape

(5, 6)

**ndim** bằng chiều dài **arr.shape**

In [52]:
print(arr.ndim)
print(len(arr.shape))

2
2


In [53]:
arr.size
#(5 * 6)

30

# **Numpy: N-dimensional arrays**

**Numpy** hỗ trợ tạo mảng n chiều. Ví dụ tạo mảng 3D với **rank** = 3 và **shape** = (3, 4, 5)

In [54]:
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

# **Numpy: Array type**

Mảng **Numpy** có kiểu **ndarrays** (N-dimensional arrays)

In [55]:
type(np.zeros((5, 6)))

numpy.ndarray

## **NumPy functions create ndarrays**

### **np.ones**
Tạo ma trận 4x5 tất cả phần tử 1

In [56]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### **np.full**
Tạo một mảng **shape** đã cho được khởi tạo với giá trị đã cho

In [57]:
np.full((3, 4), np.pi)

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

### **np.empty**
Mảng chưa được khởi tạo (không thể đoán trước được nội dung của nó, vì nó là bất cứ thứ gì trong bộ nhớ tại thời điểm đó)

In [58]:
np.empty((3, 4))

array([[3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265],
       [3.14159265, 3.14159265, 3.14159265, 3.14159265]])

### **np.array**
Khởi tạo một **ndarray** bằng cách sử dụng một mảng python thông thường. Chỉ cần gọi hàm **array**:

In [59]:
np.array([[1, 2, 3, 4], [10, 20, 30, 40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

### **np.arange**
Tạo một ndarray bằng cách sử dụng hàm **arange** của NumPy, tương tự như hàm **range** (phạm vi) của python:

In [60]:
np.arange(7, 16)

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

Cung cấp tham số **step**

In [61]:
np.arange(7, 70, 4) # step = 4

array([ 7, 11, 15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59, 63, 67])

### **np.linspace**
Hàm **linspace** trả về một mảng chứa một số điểm cụ thể được phân bố đều giữa hai giá trị (lưu ý rằng kết quả bao gồm giá trị lớn nhất và nằm ở cuối mảng)

In [62]:
np.linspace(0, 7, 5) # 5 points

array([0.  , 1.75, 3.5 , 5.25, 7.  ])

### **np.rand & np.randn**
Tạo các ndarrays được khởi tạo với các giá trị ngẫu nhiên

1. **rand** được khởi tạo với các số thực ngẫu nhiên từ 0 đến 1 (phân phối đồng đều):

In [63]:
np.random.rand(3, 4)

array([[0.35180565, 0.778027  , 0.13719446, 0.9517672 ],
       [0.38950827, 0.56488864, 0.63711332, 0.1855575 ],
       [0.35345106, 0.7813037 , 0.96529733, 0.14434714]])

2. **randn** chứa các số thực ngẫu nhiên được lấy mẫu từ phân phối chuẩn đơn biến (phân phối Gaussian) của trung bình 0 và phương sai 1:

In [64]:
np.random.randn(3, 4)

array([[ 9.60795170e-01, -5.81599673e-02, -1.54669253e+00,
        -6.69656648e-01],
       [-3.89848565e-01, -2.66142926e+00, -5.40746579e-01,
         1.11960311e+00],
       [-2.03194443e-01, -7.61372520e-04,  1.14663026e-02,
        -6.97969109e-01]])

So sánh các bản phân phối:

![alt tag](data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAYAAAAEZCAYAAACervI0AAAABHNCSVQICAgIfAhkiAAAAAlwSFlz%0AAAALEgAACxIB0t1+/AAAIABJREFUeJzt3XmcFNW5//HPwyKCyKgo4IAswQ01okYUo8YxxojGNUZF%0AXHBJRCNe703ELSYsCYmaxd1EXIh6TdBfcMOgMdw4KkQFoiAoICoOIIqiKIKiLM/vj9PD9DrTM0x1%0AdU9/369Xv7r71Kmqpwumn65zqs4xd0dERMpPq7gDEBGReCgBiIiUKSUAEZEypQQgIlKmlABERMqU%0AEoCISJlSApCSY2aHmdmSmPb9jJmdl3g9xMyeasZtzzWzbyVejzSz+5tx21eZ2bjm2p60DEoA0izM%0A7B0z+9zMVpnZe2Z2v5ltHeEuY7+Bxd3/4u6DGqpnZuPNbEwe29vL3Z9LLmpKXNkSpLv/xt0vaMr2%0ApOVSApDm4sD33L0T0B/4OnBNvCGVBjNr3dybpAgSpBQ/JQBpTgbg7h8A/wD23LTA7Bgze9nMPjWz%0AGjMbmbSsl5ltNLOzE8s+MLOrk5ZvaWZ/NrOPzWwuMCBlp2a7J5pmVprZHDM7LmnZeDO7zcwmm9ln%0AZvacmXUzsxsT9V83s/45P5DZkWY2L1H3ltrPmFg21MyeT3p/g5ktT3zG2Wa2h5n9CDgDuDxxdvRY%0Aou4iM7vczGYDq82sdaLs20m7b29mExLrzTSzvZP2tdHMvpb2OceYWQdgMlCZ+LyrEp83pUnJzI5P%0ANDl9bGb/MrPdk5YtMrOfJj7DSjP7q5ltkVjW2cwmJco/MrNncx07KX5KANLszKwHcDTwUlLxauAs%0Ad68AvgdcaGbHp616MLAL8B3gF2a2W6J8FNAn8TgKGJq0rzbAJOApYAfgv4AHzGyXpO2eAlwNdAbW%0AAS8CM4DtgInADTk+R+fE8quB7YG3EjEm80Td7wKHADsnPuOpwEfufifwAHC9u3dy9xOS1h2cOE7b%0AuPuGLCEcDzwIbAv8FXg06Wwh6y98d/88sc1l7r51Yp/vp8W6K/CXxLHaAXgSmJQ4lrVOAb5LOOb9%0AgXMS5T8FlhCOZZfEsZESpQQgzelRM1sFLCZ8WY6tXeDuz7n7a4nXc4EJwGFJ6zowyt2/cvdXgdmE%0ALx4IX0a/cvdP3f1d4Oak9Q4CtnL369x9vbs/AzwBnJ5U5xF3n+XuXwGPAGvc/QEPA2E9COyT4/Mc%0AA8x190fcfYO73wi8n6PuOmBrYA8zM3df4O7L6zlWADe5+zJ3/zLH8v/U7hv4A7AlMDCxzHKsk49T%0AgSfc/V+Jbf8OaA98My225e7+CSHB1h6jdcCOQJ/EMZm2GXFIzJQApDmdkOgDqAIOB75Ru8DMDkg0%0ANXxgZp8Awwi/qpMlf2F+DnRMvK4EliYtq0l6vSPhFylpy7vn2O4XWd53JLvKLNvOevVRIvHcCtwG%0ALDezP5lZru3WWtrA8k37SiSrpYmYNlclSccwse0l5D5myf8WvyUk96fN7E0zu6IZ4pGYKAFIc6rt%0AA3iO8GV4fdKyvwCPAt3dfRvgDvL/FfsesFPS+15Jr5elLQPoCbybf9j17rdnWln6vjZx91vdfX9g%0AD2A3YETtolyrNLD/TfsyMwN6UPe5Pgc6JNXt1ojtLiP1GNbuq6GEhLuvdvfL3L0voYnqJ2Z2eEPr%0ASXFSApCo3AgcYGYHJN53BFa6+7pE2ZC0+vUlg4eAq8xsm0T/wvCkZS8Bnyc6VNuYWRVwLKHNPF+5%0A9v13QpPOiYlO2ktJ/aKt24DZ/omznDaEs4q1wMbE4uXA17Kt14Bv1O4b+J/ENmv7VV4BhphZKzMb%0ARGpz2nKgs5l1yrHdh4DvmdnhiWN2WWLbLzQUkJl9z8z6Jt5+Bqyn7nNKiVECkOaS8qvT3VcAfwau%0ATBRdDPzSzD4lXB76YH3rp70fTehXWETo7L0vaT/rgOMI7fUrCGceZ7n7whzbbTD2pG1/ROh/uC6x%0A7b7A1Bzb6ATcCXyciHMFobkE4G5gz8QVNw/Xs8/0sseA04CVhCuJTkrqLP5vwi/wlYT+jkeS4l5A%0ASIBvJ/aZkrTc/Q3gTMKx+pDQKX+cu6+vJ7ZauwBTzOwzYBpwm7vrSqASZZoQRkSkPOkMQESkTCkB%0AiIiUKSUAEZEypQQgIlKm2jRcpTiYmXqrRUSawN2zXupcUmcA7h77Y+TIkbHHUCwPHQsdCx2L4j8W%0A9SmpBCAiIs1HCUBEpEwpATRSVVVV3CEUDR2LOqV0LDZuhA3ZBp9uJqV0LKJW7MeiZO4EDiPslkas%0AIvk4/3xo1QruvLOw+z37bLj/ftCfU3kwM7wldAJn07t3b8xMjyY8evfuHfc/X1m75x64667C73dp%0Ag2N+ZvrwQ7j4Yli2rPnjkfiUfAKoqamJvZe9VB81NTUNH2CJlOUYh3TChLBs8eLCxpPL1Klw++3w%0AzDNxRyLNqeQTgEhLtGhReF6xIr/6NTUwYgR89ll0MUnLowQg0sxqasKv90ceqSsbPz6UpX+hu8PI%0AkfBlrkkh8zRpEvzud/Cf/2zedqS8KAGINLPlickUp0+Hb30LXngB3ngjlK1cmVl/zBhYuDCzPBt3%0AeLc55joTQQmgpI0ePZqzzjor7jAkh7ffhuefh//6L/j735tnm3/+M/ToAa+91jzbq8+oUeEqJV0t%0A1HK1yATQu3c43Y7qUUwXz1iuXkQpGjNnwpw54fWKFeE6/IbMmBGeR41KvWa/9gxi1arc6956K1xy%0ASWa5O/zxj/Dyy+H90qV1r7OZMyesowTQcrXIBFBTU/cfN4pHUy+e2RDl3TdSEr75TbjjjvrrvPNO%0A6D+46abQtv/73zduH7feGh7p1qyBH/8YPv00vD//fPjGNzLr/epXsM020Lp14/YrpadFJoBi0qdP%0AH66//nr69+9Px44dGTt2LDvvvDOdOnVir7324tFHH91U99577+XQQw9lxIgRbLfddvTt25ennnpq%0A0/J33nmHqqoqKioqOOqoo1iR7yUiUlBr19a//KOPMstuuaXuh8X69dC3b2g6uvba7PWHDcu9/S23%0AzC/OXL/sZ86sSxK176VlijQBmNndZrbczF6tp87NZrbQzGaZ2T5RxhOXCRMm8OSTT/LJJ5+w++67%0AM23aNFatWsXIkSM588wzWV7bawhMnz6dfv368dFHHzFixAjOP//8TcuGDBnCgAEDWLFiBddccw33%0A3ntvHB9HGnDCCY1fZ9w4uPvu/OoeeywsWRL6FyZNym+dqVMbPpP4zW+gTx9okzRIvBmMHZvfPqT0%0ARH0GMB44KtdCMzsa6OvuuwDDgD9FHE8sLr30UiorK2nXrh0nn3wyXbt2BeCUU05hl112Yfr06Zvq%0A9urVi/POOw8zY+jQobz33nt88MEHLFmyhJkzZzJmzBjatm3LoYceynHHHRfXR5J6bL01nHpqdNvv%0A0CE8TjsNjj8+d70XXwy/8levhkMPDf0JEK44Sj5L+PWvoV+/kCTeeQdef71u2SmnpCaEhx+GV15p%0Azk8jcYo0Abj7VCDLhW+bnADcl6j7ElBhZl2jjCkOPXr02PT6vvvuY99992Xbbbdl22235bXXXktp%0AyunWrdum1+3btwdg9erVLFu2jG233XZTGYRkIcWjpiZc+bNkSdPW37gx3C9w1135dRQ31NRz0EEw%0AbVrY1tZbwyGHhPLu3VPrVVfD/Pl1X/Tz5uXe5sMPw2WXNRyblIa4ZwTrDiT/ubybKFuevXppqr1S%0AZ/HixVxwwQU888wzHHTQQQDsu+++DU7aALDjjjuycuVKvvjii01JYPHixbRqpW6cYlF7dViHDrD9%0A9pk3ffXrF9r3f/7z8Es73cKFcNtt8MknTY/hhBNSrxBau7bh0T/btk19f+qp8NBDuevXXho6axb0%0A7x/eS2nSP10BrVmzhlatWrH99tuzceNGxo8fz9y5c/Nat2fPnuy///6MHDmSdevWMXXqVCbl2wAs%0ABTVmDLRvD08/nVp+5pl1TUO52vu7dIGttmrafo86Knz577FHGErim98M5cOGweef514v3+Ej9tkH%0ArrsOpkwJSWy//eDCC5sWqxSHuM8A3gV2SnrfI1GW1ajaRkzCONu5xtru1Sv3IFvNoTEtL8nX6ffr%0A14+f/vSnDBw4kNatW3P22WdzSO15eR7rP/DAAwwdOpTOnTtz0EEHMXToUD7ZnJ+L0ixuuy384k82%0AZEj9na5t28K6dallM2eG9vpc1q0LiWOvvbIvr41h0KBwNtK+fd0v9aeeCpd3Jqtt8nn++dz7BHjz%0ATXjyybDNyy8P27vjDujYMQxl/Z3vRNvnIY1TXV1NdXV1fpULMB9lb2BOjmXHAH9PvB4IvFjPdjyb%0AXOXSMB275gHuXbrU3Sny0EN15cmPsWPdf/az8Lpt2+x3mVx+uftWW4XX7u7XXhvK3N1rakL5Sy+5%0AV1a69+kT3k+e7D54sPvFF7u/+ab7mjWh/skn12130SL3Qw4Jrz//3H3LLd2PPdb9wQfdx40L5ccf%0AH56///3wvN9+7qeeWreNY48N250yJbw/4gj3ESPC64MPdv/qq4IedslT4u886/dq1JeB/gX4N7Cr%0AmS02s3PNbJiZXZD4Rp8MLDKzN4E7gB9HGY9IVD74ADp1Cm37p5zS9O2ccUb9y3faqa4Tt0OH8HzM%0AMWH4aAj3D9SW104088Mf5r57vX17OPfc8Prxx8Pz4YeHR667hI84ou517Un4tGkN3/8gxSfqq4CG%0AuHulu7dz957uPt7d73D3cUl1hrv7zu7e393ruTFdpDjVfuGuWpV6Zc5JJzXP9idMgC++yCyvqAjj%0A87/3Xvb16msGXbu2bmKYNm3qLhGdOBGGD4eLLsovtgEDYOjQ/OpK8VEnsMhmqqiABQtg9mzomnQR%0A88MPhzbzZBdeCJdeCrvsUldWVVX3SzrdueeGSWHGjg19T+mXmLZtW/dFn++YPe3ahSEgZs2qK0uO%0AB0IH8pAhod/glltCWZcumdvaYYcwQF3HjiGhaNyg0qIEINIMOnaEvfduuF6PHmEMnuRr7Y88EgYP%0ADq8rKlLrd+kSrupJvxt35cpwSSnAdtuFbX7/+/Xvu7bTuVWruu3tsEP2ut27wwMPhMQwfHg4Axk3%0ALntdCJ3Xe+wRtr25cxtI4cR9FZBI2endO3zRf/JJuKpn8ODQFj9kSLhhK93tt4czhHbt4Kqrwrpf%0AfBHmG4BwFlDf3MK1N5VVVdXdY3DUUWG8n06d8os5201n6VcxHXhgmJBm7doQqxQ/nQGIFNjWW8Po%0A0eH1d78b+hDMsn/5Q91lx5dcEmYP69gR7r8/lG2zTe79dOwIZ51V1xdx7bXhjt9a+X75Z7PTTnDw%0AwallrVvX9YdIadAZgEgMhg8PN4Ztt13T1j/jDDj6aOjcOXedNm3gvvuatv2GFMtk9bJ5dAYgEoNW%0ArXJ/+a9Z0/D6ZvV/+cdBbf+lR2cAJWz06NG8+eab3F/bHiAtwiOPwFdfFXaftU1J9TUp1eeuu0Lf%0ARkMd0VJcWmYC6N276dN25aNXr+yjecVAU0K2PCeeWPh9HnNM+JPp2bNp6ydNWyElpGUmgNo5IaPS%0AxC/dDRs20Frz7JWVUrouvqlf/lK61AcQsUJNCVlTU0OrVq2477776NWrF126dOHXv/51QT+rZOrb%0AN+4IRHJTAiiAQk4JOW3aNBYuXMiUKVMYM2YMCxYsKMhnlOyGDQvXxosUIyWAAijUlJBmxqhRo9hi%0Aiy3Ye++96d+/P7Nnzy7oZ5VMtVfrNLWJpfb+ADXRSHNrmX0ARSZ9SsgbbriBdxKdyGvWrMlrSsgP%0AP/ww65SQS2tH9EromjQYTYcOHVhd3wDzUhC9eoVhG5ra/dO5c5jRS/390tyUAApAU0LK5vb9659Z%0AoqD/VgUU9ZSQ+SQSEZFaLTMB1M4JGdWjEXNC5poSslu3brz22muNnhLyxRdfpHPnzvzyl79kaNpA%0A7On3BOgeARGpj5XKr0Yz82yxmpl++TaRjl3zqKwM8/lWVsYdSfwqKsI4QenDWkt8En/nWX8Ntswz%0AABERaZASgIhImVICEBEpU0oAIiJlSglARKRMKQGIiJSpkr8TuFevXrrevYl6NeJ+BhFpeUo+AbxT%0AJBOziIiUGjUBiYiUKSUAEZEypQQgIlKmlABERMqUEoCISJlSAhARKVNKACIiZSryBGBmg8xsvpm9%0AYWZXZFne2cyeNLNZZjbHzM6JOiYREYk4AZhZK+BW4ChgT+B0M9s9rdpwYJa77wMcDvzezEr+BjUR%0AkWIX9RnAAcBCd69x93XABOCEtDrvA1snXm8NfOTu6yOOS0Sk7EX9S7s7sCTp/VJCUkh2J/B/ZrYM%0A6AicFnFMIiJCcYwFdBUw290PN7O+wD/NbG93X51ecdSoUZteV1VVUVVVVbAgRURKQXV1NdXV1XnV%0AjXRSeDMbCIxy90GJ91cC7u7XJdWZDIx192mJ9/8HXOHuM9O2lXVSeJG4aVL4OpoUvvjEOSn8DGBn%0AM+tlZlsAg4HH0+rMA74DYGZdgV2BtyOOS0Sk7EXaBOTuG8xsOPA0Idnc7e7zzGxYWOzjgN8A481s%0ANmDA5e7+cZRxiYhIAfoA3P0pYLe0sjuSXq8Ajos6DhERSaU7gUVEypQSgIhImVICEBEpU0oAIiJl%0ASglARKRMKQGIiJQpJQARkTKlBCAiUqaUAEREypQSgIhImVICEBEpU0oAIiJlSglARKRMKQGIiJQp%0AJQARkTKlBCAiUqaUAEREypQSgIhImVICEBEpU0oAIiJlSglARKRMKQGIiJQpJQARkTKlBCAiUqaU%0AAEREypQSgIhImVICEBEpU0oAIiJlSglARKRMKQGIiJSpvBKAmT1sZt8zMyUMEZEWIt8v9NuBIcBC%0AM7vWzHaLMCYRESmAvBKAu09x9zOA/YB3gClm9m8zO9fM2ta3rpkNMrP5ZvaGmV2Ro06Vmb1iZnPN%0A7JnGfggREWm8vJt0zKwzcA7wQ+AV4CZCQvhnPeu0Am4FjgL2BE43s93T6lQAtwHHuvtewCmN+wgi%0AItIUbfKpZGaPALsB9wPHuft7iUUPmtnMelY9AFjo7jWJ7UwATgDmJ9UZAkx093cB3H1F4z6CiIg0%0ARV4JALjT3ScnF5hZO3f/0t33r2e97sCSpPdLCUkh2a5A20TTT0fgZne/P8+4RESkifJNAL8CJqeV%0AvUBoAmqOGPYDvg1sBbxgZi+4+5vpFUeNGrXpdVVVFVVVVc2wexGRlqO6uprq6uq86tabAMysG+FX%0AfHsz2xewxKJOQIc8tv8u0DPpfY9EWbKlwAp3XwusNbPngP5AvQlAREQypf84Hj16dM66DZ0BHEXo%0A+O0B/CGp/DPg6jximQHsbGa9gPeAwcDpaXUeA24xs9ZAO+DAtH2JiEgE6k0A7n4vcK+ZnezuExu7%0AcXffYGbDgacJVxzd7e7zzGxYWOzj3H2+mf0DeBXYAIxz99cb/1FERKQxzN1zLzQ7093/18x+CmRU%0AdPeC/VI3M68vVpG4VFbCzJnhudxVVMDixeFZioOZ4e6WbVlDTUBbJZ47Nm9IIiISt4aagO5IPOfu%0ARRARkZKU72Bw15tZJzNra2b/Z2YfmtmZUQcnIiLRyXcoiO+6+yrgWMJYQDsDI6IKSkREopdvAqht%0AKvoe8P/c/dOI4hERkQLJ907gJ8xsPvAFcJGZ7QCsjS4sERGJWr7DQV8JfBPY393XAWsIg7qJiEiJ%0AyvcMAGB3oLeZJa9zXzPHIyIiBZLvcND3A32BWYS7dSHcGKYEICJSovI9A9gf2EO34oqItBz5XgU0%0AF+gWZSAiIlJY+Z4BbA+8bmbTgS9rC939+EiiEhGRyOWbAEZFGYSIiBReXgnA3Z9NjOm/i7tPMbMO%0AQOtoQxMRkSjlOxbQj4C/AXckiroDj0YVlIiIRC/fTuCLgYOBVQDuvhDoElVQIiISvXwTwJfu/lXt%0Am8TNYLokVESkhOWbAJ41s6sJk8MfCfw/YFJ0YYmISNTyTQBXAh8Cc4BhwGTgmqiCEhGR6OV7FdBG%0AM3sUeNTdP4w4JhERKYB6zwAsGGVmK4AFwILEbGC/KEx4IiISlYaagP6HcPXPAHffzt23Aw4EDjaz%0A/4k8OhERiUxDCeAs4HR3X1Rb4O5vA2cCZ0cZmIiIRKuhBNDW3VekFyb6AdpGE5KIiBRCQwngqyYu%0AExGRItfQVUD9zWxVlnIDtowgHhERKZB6E4C7a8A3EZEWKt8bwUREpIVRAhARKVNKACIiZUoJQESk%0ATEWeAMxskJnNN7M3zOyKeuoNMLN1Zvb9qGMSEZGIE4CZtQJuBY4C9gRON7Pdc9S7FvhHlPGIiEid%0AqM8ADgAWunuNu68DJgAnZKl3CWHKyQ8ijkdERBLyGg56M3QHliS9X0pICpuYWSVworsfbmYpy0SK%0A0nnnwdtvb3r7t4+g8w+A006CSy+NLy6RRoo6AeTjRiC5b8DiCkRaOHeYOBFWr04tnzMHpkyBDh1S%0Ayz//HE49Fbp3Ty0fPz7Ubx3uk/z9yXDPkS/T7rHHMhPAnXfCsGGZsXToEPbbp89mfiiRpos6AbwL%0A9Ex63yNRlmx/YIKZGbA9cLSZrXP3x9M3NmrUqE2vq6qqqKqqau54pSWbMwcuuACOPz61fONGuOgi%0A6N8/tfyZZ2D+fFi4MLX85z+Hb38bLPxWeaEdrNtzIzzzaGZyWbAAxoyBq69OLT/wQPjwQyUAaXbV%0A1dVUV1fnVdfco5vb3cxaEyaSOQJ4D5hOGF56Xo7644FJ7v5wlmUeZaxSBmbNgnPOCc/NqLISXpmw%0AgK4nfRO+/DKzwvjxcMopqWUHHAC33hqeW5CKCli8ODxLcTAz3D1ry0qkZwDuvsHMhgNPEzqc73b3%0AeWY2LCz2cemrRBmPSFQ27LwbfPRR41a65x54+unUst12y0wWIhGJvA/A3Z8CdksruyNH3fOijkek%0AKIweDdOmwdq1dWVr18KZZ4Zmp3SDBsGAAYWLT8pCMXQCi5Sfo48Oj2TuoU/g/fdTy+fNC81WEycW%0ALj4pC0oAIsXCDC6+OLN84kT43e/gsccy6w8aBFtsUZj4pMVRApCW6Yor4NVXU8tWrYK2JTiT6YAB%0AsOOOoc8g2ezZcM018MMfxhOXlLxIrwJqTroKSBpl++3DVTbpl6Pstht87WvNuqvKSpg5MzwX1M9/%0ADjfemHn/wjbbwAsvwHbbFTggXQVUjGK7Ckgkcn/8Y3ik++KL0Mbekr+JRo6E4cMzyw88ED7+OJYE%0AIKVFCUBK23PPwZAhcMwxqeUVFS37yx+gTRvo2jV7+ZQp8PrrqeW77AL9+hUmNikJSgBSGmbPhgsv%0ADFfKJFu4EAYPhr33jieuYnT++TB5cmrZmjWhbSb9rmYpa0oAUhpmzgzt+j/7WWp5q1a6Pj7dVVdl%0Ali1aFIavEEmiBCClo0sXGDgw7ihEWgwlACkun30Ghx8eOjGTrVoVxvERkWajBCDFZeVKWLYMpk7N%0AXJY+LLOIbBYlACk+bdo0+7X6IpIp8knhRaQIdOwIK1aEewPSHzfcEHd0EhOdAYiUgx12gPfeg6++%0ASi2/7z547bV4YpLYKQFIfC65BJ59NrXsq69g663jiael69gxs2yrrQofhxQNJQCJzz/+EUa57N07%0Atbxbt1jCESk3SgASvQ0b4NNPs5fvvjvsumvhYxIRJQApgLFj4dprYcstU8srKjRgWTFYsCBzqOnW%0ArcMQG+3axROTFIQSgERv+XL47W+zT3Yi8TrySHjxxcz7Lp55Btq3h1NPjScuKQglAJFy1rs33H13%0AZvk554TJZm66KbW8a1eYMEGzkLUQSgDSfFasgDFjYP361PLnnoM99ognJmmaG27IHE4awhSUq1er%0A6a6FUAKQ5vP88+GyzmHDUsv32gvOOCOemKRptt0WDj44s7wUp9SUnJQApHl97Wvw4x/HHYVExSzc%0Av5HeOfytb2mwvhKkBCAi+Xv00cxJZWpq4OablQBKkBKAiOTv0EPDI9nLL8OkSfHEI5tFCUAab906%0AOPbYMLZMsk8/hcMOiycmEWk0JQBpvLVrQ4fviy9mLuvTp/DxiEiTKAFI07RurYnYpc7SpXDZZfxq%0ALWx5DVDbR3zuubDnnnFGJvXQfAAisnn694fRo6FbN5ZbNzZ27RYG9Hv99TDctBQtnQFI/WbNgpkz%0AU8vWro0nFilOrVvDRRcBcMsvYcQl0L6CMNhf+tzOUlSUAKR+F10UJhPp0iW1/Be/iCceEWk2SgBS%0AP3e4+moYODDuSESkmUXeB2Bmg8xsvpm9YWZXZFk+xMxmJx5TzezrUcckIiIRnwGYWSvgVuAIYBkw%0Aw8wec/f5SdXeBr7l7p+a2SDgTkA/N0Vago8/hjfeSC1r21aXCxeJqJuADgAWunsNgJlNAE4ANiUA%0Ad0++mPxFoHvEMUk2//u/YYyXdGvXauRHaZp99w1DTafP+/zuu/Cvf8GBB8YTl2wSdQLoDixJer+U%0AkBRy+SHwZKQRSXbz54dB3C67LLW8TRtN0i5N893vZv76BzjuOPjRjzJ/WPTqBX/+cxhwTgqiaDqB%0Azexw4FzgkFx1Ro0atel1VVUVVVVVkcdVVtq3D8MAi0Tprrtg3rzM8sMPDwlANkt1dTXV1dV51TV3%0AjywQMxsIjHL3QYn3VwLu7tel1dsbmAgMcve3cmzLo4y1bKxfD+PHZ17L/8QTYZCva66JJ64SVlkZ%0AbpWorIw7kvhVVMDixeG50cxg40adATQzM8Pdsx7UqM8AZgA7m1kv4D1gMHB6WnA9CV/+Z+X68pdm%0ANG0ajBwJJ5+cWr7rrvCDH8QTk4jEItIE4O4bzGw48DThktO73X2emQ0Li30c8HNgO+B2MzNgnbvX%0A108gm2uXXeCWW+KOQiRVhw5wwAGZZwCnnAIjRsQTUwsXeR+Auz8F7JZWdkfS6x8BP4o6DhEpcnPn%0AwocfppZNnx4moVECiETRdAKLSJnr0yfz/oBVq+KJpUwoAbRkK1fCZ5+lli1fHk8sIlJ0lABast13%0Ahy22yGxTPe20eOIRkaKiBNCSffwxfP55uPVepBS1bw8zZsAhWW4Puvba7OWSNyUAESleBx8MU6bA%0Al1+mlv/d05sFAAAJPUlEQVTxjzB1qhLAZlICEJHiNmBAZtkTTxQ+jhZICaAl+PRTWLQos1x3TktL%0AZQZ/+xssXJhavtVW8JvfhGdpkBJAKZkxA668MrP8X/+CTp0yL6E7+ugwXZ9IS/Pf/w0775xZPmYM%0ADB0K3/hG4WMqQUoApeT558NgbYn5VzcZOTKM46MxVKRcdO0K55+fWX777YWPpYQpAZSanj3hiCPi%0AjkKkOPXsmX04iX32CSP2SQolABFpOSZODCOKJlu5Mgx2KBmUAIrRsmXQv3/mXbzr18P118cTk0gp%0AaNUqPJK10ddcLjoyxWjFitDGuWRJ5rJ27Qofj4i0SEoAxapVK9hyy7ijEJEWTAkgbiedlNk59dVX%0AsMce8cQj0tK0bQvr1kG/fpnLLrwQLr208DEVCSWAuP373/Dkk7DDDqnl6RNmi0jTdOwICxZkDi39%0A5JNhhjwlAIlV9+6hzV9EotG9e3gkmzMnJIY//CG13AzOPRe22aZw8cVECaBQnn02XKKWThNeiMTj%0A298Od9cvXZpa/s9/hqEkLrggnrgKSAmgUMaNC8My7L9/avk990CXLvHEJFLOtt8efvvbzPIy+OKv%0ApQTQ3D77DMaPz7wZZf58+MlP4Iwz4olLRPKz005huJWLL04t33ZbmDcPOneOJ64ItGq4ijTKxInw%0Apz/BO++kPg47DI48Mt7YRKRh11wDa9eGyZSSH1ttBe+/n1m+fn3cETeZzgCicMABcOONcUchIk1h%0Aln0WvX79Mucm2Lgx/L0/91xhYmtmSgAiIvmYPDmz7K23YODA0Oyb7sgjoUeP6OPaDEoATbVqVRhz%0A/KOPUsu//BKGD48nJhEprB494MwzM88A5s+Hl14KzcFFTAkgmXv2WbTOOivMS5psw4ZwXfFLL2XW%0Ar6iIJj4RKS7t2sENN2SW33EHvPxy4eNpJCWAZL//PYwYkTmWeEVFmIB6++1Tyzt21NRzIpJpyy3h%0A8cfDjWbJWrcOl4T37RtPXGmUAJLV1MDNN8Mll8QdiYiUsjPPhN69M1sURo6EX/wCvv711PJu3cJU%0AlgWe1a88E8Ann8B112VevjV1qiaOEJHN17p1uPQ73dix8MQT4Tso2ciRcOKJBR9+wjxbm3cRMjNv%0AdKzr14fpE999N7X8rbfC4GsjRmSuc955LepGD4leZWUY0LWyMu5I4ldRAYsXqxus0Xr0CDeapU9e%0Ac8wxIWlsBjPD3bOeWrScM4C33oJXX00t+/LL0Ek7d25m/cpK6NChMLGJiNTnpZfggw9Sy958M0x8%0A/5//ZNa//PIwltFmajkJ4Nxzw3P6r/dLL4Wddy58PCIi+co2Wum++4a+gTVrUssnT4bTToMdd0wt%0Ab9cO/vY36NUr791G3gRkZoOAGwnDTtzt7tdlqXMzcDSwBjjH3WdlqeM+fXpoP7vxxszx8pcvh+nT%0AYa+9ovgYIjmpCaiOmoAKYMMGeO21zPKLLgrPaYNL2qOP5mwCijQBmFkr4A3gCGAZMAMY7O7zk+oc%0ADQx39++Z2YHATe4+MMu23PffP2TDn/wktO0n22KLzAwagerqaqqqqiLfTynQsQgqK+Hmm6v5wQ+q%0A4g4ldhUV8MAD1Rx7bFXcoRSFgv6NLFoEs9J+O7tjJ58cWx/AAcBCd68BMLMJwAnA/KQ6JwD3hVj9%0AJTOrMLOu7r48Y2szZkQcbsP0pVdHx6LOCy8oAdSaOlUJoFZB/0b69AmPRoh6NNDuwJKk90sTZfXV%0AeTdLHRERaWYaDlpkM33969BKf0kA7LNPwe9lks0QdR/AQGCUuw9KvL8S8OSOYDP7E/CMuz+YeD8f%0AOCy9CcjMSuOGBRGRIhNXH8AMYGcz6wW8BwwGTk+r8zhwMfBgImF8kq39P9cHEBGRpok0Abj7BjMb%0ADjxN3WWg88xsWFjs49x9spkdY2ZvEi4DPTfKmEREJCiZoSBERKR5qeuqkczsejObZ2azzGyimXWK%0AO6a4mNkPzGyumW0ws/3ijicOZjbIzOab2RtmdkXc8cTFzO42s+Vm9mrDtVs2M+thZv8ys9fMbI6Z%0A/VfcMeWiBNB4TwN7uvs+wELgqpjjidMc4CTg2bgDiUPiRsdbgaOAPYHTzWz3eKOKzXjCcRBYD/zE%0A3fcEDgIuLtb/F0oAjeTuU9x9Y+Lti0BxT/oZIXdf4O4LgXLtoN90o6O7rwNqb3QsO+4+FVgZdxzF%0AwN3frx3Oxt1XA/Mo0nublAA2z3nAk3EHIbHJ50ZHKWNm1hvYB8gyd2z8Ws5ooM3IzP4JdE0uAhz4%0AmbtPStT5GbDO3f8SQ4gFk8+xEJFMZtYR+BtwaeJMoOgoAWTh7kfWt9zMzgGOATZ/QO4i19CxKHPv%0AAj2T3vdIlEmZM7M2hC//+939sbjjyUVNQI2UGN56BHC8u38ZdzxFpBz7ATbd6GhmWxBudHw85pji%0AZJTn/4Ns7gFed/eb4g6kPkoAjXcL0BH4p5m9bGa3xx1QXMzsRDNbAgwEnjCzsuoPcfcNQO2Njq8B%0AE9x9XrxRxcPM/gL8G9jVzBabWdne0GlmBwNnAN82s1cS3xOD4o4rG90IJiJSpnQGICJSppQARETK%0AlBKAiEiZUgIQESlTSgAiImVKCUBEpEwpAYgkJIbwPTKt7FIzu62edT6LPjKRaCgBiNT5C5lTlg4G%0A/lrPOrqRRkqWEoBInYnAMYlxXEjMZb0j8IqZTTGzmWY228yOT1/RzA4zs0lJ728xs7MTr/czs2oz%0Am2FmT5pZ1/T1ReKgBCCS4O4rgenA0YmiwcBDwBfAie6+P2EAwN/n2kR6QSKZ3AKc7O4DCBOn/LqZ%0AQxdpEo0GKpJqAuGLf1Li+TzCD6VrzexQYCNQaWZd3P2DPLa3G7AXYewoS2xrWSSRizSSEoBIqseA%0AP5jZvkB7d3/FzIYCnYF93X2jmS0Ctkxbbz2pZ9S1yw2Y6+4HRx24SGOpCUgkibuvAaoJw/nWTvZT%0AAXyQ+PI/HOiVtErt8Mc1wB5m1tbMtgGOSJQvAHYws4EQmoTMbI+IP4ZIXnQGIJLpr8DDwGmJ9w8A%0Ak8xsNjCTMMdrLQdw96Vm9hAwF1gEvJwoX2dmPwBuMbMKoDVwI/B6IT6ISH00HLSISJlSE5CISJlS%0AAhARKVNKACIiZUoJQESkTCkBiIiUKSUAEZEypQQgIlKmlABERMrU/wdV51xrmy463wAAAABJRU5E%0ArkJggg==%0A)

### **np.fromfunction**

In [65]:
def my_function(z, y, x):
    return x + 10 * y + 100 * z

np.fromfunction(my_function, (3, 2, 10))

array([[[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
        [ 10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.]],

       [[100., 101., 102., 103., 104., 105., 106., 107., 108., 109.],
        [110., 111., 112., 113., 114., 115., 116., 117., 118., 119.]],

       [[200., 201., 202., 203., 204., 205., 206., 207., 208., 209.],
        [210., 211., 212., 213., 214., 215., 216., 217., 218., 219.]]])