![alt tag](https://codelearn.io/Upload/Blog/thu-vien-numpy-trong-python-63724882299.0039.png)

# **What is Numpy?**
**NumPy** là thư viện cơ bản cho tính toán khoa học bằng Python. Nó là một thư viện Python cung cấp một đối tượng mảng đa chiều, các đối tượng dẫn xuất khác nhau (chẳng hạn như các mảng và ma trận có mặt nạ) và một loạt các quy trình cho các hoạt động nhanh trên mảng, bao gồm toán học, logic, thao tác hình dạng, sắp xếp, lựa chọn, I / O , các phép biến đổi Fourier rời rạc, đại số tuyến tính cơ bản, các phép toán thống kê cơ bản, mô phỏng ngẫu nhiên và hơn thế nữa.

# **Reference**
https://github.com/ageron/handson-ml2/blob/ce94de16f017f78b0991a3d3ae18b3de70b15118/tools_numpy.ipynb

# **Numpy: Import**
Import thư viện **numpy**. Hầu hết mọi người sử dụng nó dưới dạng **np**

In [28]:
import numpy as np

# **Array Data**

### **dtype**
Các **ndarrays** của **Numpy** có tất cả các phần tử cùng kiểu (thường là số). Bạn có thể kiểm tra kiểu dữ liệu bằng cách xem thuộc tính **dtype**:

In [29]:
arr = np.arange(1, 5)
print(arr.dtype)
arr

int64


array([1, 2, 3, 4])

In [30]:
arr2 = np.arange(1.0, 5.0)
print(arr2.dtype)
arr2

float64


array([1., 2., 3., 4.])

Thay vì để **Numpy** đoán loại dữ liệu, bạn có thể đặt nó một cách rõ ràng khi tạo mảng bằng cách đặt tham số **dtype**:

In [31]:
arr3 = np.arange(1, 5, dtype = np.complex64)
print(arr3.dtype)
arr3

complex64


array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j], dtype=complex64)

**Các loại dữ liệu có sẵn bao gồm**

| Data type | Description |
| --- | --- |
| bool_ | Boolean (True or False) stored as a byte |
| int_ | Default integer type (same as C long; normally either int64 or int32) |
| intc | Identical to C int (normally int32 or int64) |
| intp |	Integer used for indexing (same as C ssize_t; normally either int32 or int64) |
| int8 |	Byte (-128 to 127) |
| int16	| Integer (-32768 to 32767) |
| int32	| Integer (-2147483648 to 2147483647) |
| int64	| Integer (-9223372036854775808 to 9223372036854775807) |
| uint8	| Unsigned integer (0 to 255) |
| uint16 |	Unsigned integer (0 to 65535) |
| uint32 |	Unsigned integer (0 to 4294967295) |
| uint64 |	Unsigned integer (0 to 18446744073709551615) |
| float_ |	Shorthand for float64 |
| float16 |	Half precision float: sign bit, 5 bits exponent, 10 bits mantissa |
| float32 |	Single precision float: sign bit, 8 bits exponent, 23 bits mantissa |
| float64 | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa |
| complex_	| Shorthand for complex128 |
| complex64	| Complex number, represented by two 32-bit floats (real and imaginary components) |
| complex128 | 	Complex number, represented by two 64-bit floats (real and imaginary components) |

### **itemsize**
Trả về kích thước (tính bằng byte) của mỗi phần tử:

In [32]:
arr6 = np.arange(1, 5, dtype=np.int8)
arr6.itemsize

1

In [33]:
arr4 = np.arange(1, 5, dtype=np.float64)
arr4.itemsize

8