![alt tag](https://codelearn.io/Upload/Blog/thu-vien-numpy-trong-python-63724882299.0039.png)

# **What is Numpy?**
**NumPy** là thư viện cơ bản cho tính toán khoa học bằng Python. Nó là một thư viện Python cung cấp một đối tượng mảng đa chiều, các đối tượng dẫn xuất khác nhau (chẳng hạn như các mảng và ma trận có mặt nạ) và một loạt các quy trình cho các hoạt động nhanh trên mảng, bao gồm toán học, logic, thao tác hình dạng, sắp xếp, lựa chọn, I / O , các phép biến đổi Fourier rời rạc, đại số tuyến tính cơ bản, các phép toán thống kê cơ bản, mô phỏng ngẫu nhiên và hơn thế nữa.

# **Reference**
https://github.com/ageron/handson-ml2/blob/ce94de16f017f78b0991a3d3ae18b3de70b15118/tools_numpy.ipynb

# **Numpy: Import**
Import thư viện **numpy**. Hầu hết mọi người sử dụng nó dưới dạng **np**

In [26]:
import numpy as np

# **Reshaping an array**

### **shape**
Thay đổi hình dạng của một **ndarray** đơn giản như thiết lập thuộc tính **shape** của nó. Tuy nhiên, kích thước của mảng phải được giữ nguyên.

In [27]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [28]:
a.shape = (6, 5) # a*b = 30
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [29]:
a.shape = (2, 3, 5) # a*b*c = 30
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

### **reshape**
Hàm **reshape** trả về một đối tượng **ndarray** mới trỏ vào cùng một dữ liệu. Điều này có nghĩa là việc sửa đổi một mảng cũng sẽ sửa đổi mảng kia.

In [30]:
aa = a.reshape(5, 6)
print("Array aa is:\n", aa, "\n")
print("Array a is:\n", a)

Array aa is:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] 

Array a is:
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


Thiết lập giá trị 100 cho phần tử hàng 4, cột 2 thành 100 ở mảng **aa**, phần tử tương ứng trong mảng **a** cũng được sửa đổi

In [31]:
aa[4, 2] = 100
print("Array aa is:\n", aa, "\n")
print("Array a is:\n", a)

Array aa is:
 [[  0   1   2   3   4   5]
 [  6   7   8   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]
 [ 24  25 100  27  28  29]] 

Array a is:
 [[[  0   1   2   3   4]
  [  5   6   7   8   9]
  [ 10  11  12  13  14]]

 [[ 15  16  17  18  19]
  [ 20  21  22  23  24]
  [ 25 100  27  28  29]]]


### **ravel**
hàm **ravel** trả về một **ndarray** một chiều mới cũng trỏ đến cùng một dữ liệu

In [32]:
aa.ravel()

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
       100,  27,  28,  29])