![alt tag](https://codelearn.io/Upload/Blog/thu-vien-numpy-trong-python-63724882299.0039.png)

# **What is Numpy?**
**NumPy** là thư viện cơ bản cho tính toán khoa học bằng Python. Nó là một thư viện Python cung cấp một đối tượng mảng đa chiều, các đối tượng dẫn xuất khác nhau (chẳng hạn như các mảng và ma trận có mặt nạ) và một loạt các quy trình cho các hoạt động nhanh trên mảng, bao gồm toán học, logic, thao tác hình dạng, sắp xếp, lựa chọn, I / O , các phép biến đổi Fourier rời rạc, đại số tuyến tính cơ bản, các phép toán thống kê cơ bản, mô phỏng ngẫu nhiên và hơn thế nữa.

# **Reference**
https://github.com/ageron/handson-ml2/blob/ce94de16f017f78b0991a3d3ae18b3de70b15118/tools_numpy.ipynb

# **Numpy: Import**
Import thư viện **numpy**. Hầu hết mọi người sử dụng nó dưới dạng **np**

In [2]:
import numpy as np

# **Conditional operators**
Các toán tử điều kiện cũng áp dụng theo từng phần tử tương ứng với vị trí

In [3]:
m = np.array([100, 200, -300, 400])
m < [101, 112, -400, 300]

array([ True, False, False, False])

Sử dụng **Broadcasting**

In [4]:
m < 250

array([ True,  True,  True, False])

Tìm phần tử theo điều kiện cho trước

In [6]:
m[m < 300]

array([ 100,  200, -300])