![alt tag](https://codelearn.io/Upload/Blog/thu-vien-numpy-trong-python-63724882299.0039.png)

# **What is Numpy?**
**NumPy** là thư viện cơ bản cho tính toán khoa học bằng Python. Nó là một thư viện Python cung cấp một đối tượng mảng đa chiều, các đối tượng dẫn xuất khác nhau (chẳng hạn như các mảng và ma trận có mặt nạ) và một loạt các quy trình cho các hoạt động nhanh trên mảng, bao gồm toán học, logic, thao tác hình dạng, sắp xếp, lựa chọn, I / O , các phép biến đổi Fourier rời rạc, đại số tuyến tính cơ bản, các phép toán thống kê cơ bản, mô phỏng ngẫu nhiên và hơn thế nữa.

# **Reference**
https://github.com/ageron/handson-ml2/blob/ce94de16f017f78b0991a3d3ae18b3de70b15118/tools_numpy.ipynb

# **Numpy: Import**
Import thư viện **numpy**. Hầu hết mọi người sử dụng nó dưới dạng **np**

In [ ]:
import numpy as np

# **Mathematical and statistical functions**
Nhiều hàm toán học và thống kê có sẵn cho **ndarrays**

### **ndarrays** method
Một số hàm đơn giản là các phương thức **ndarray**

In [ ]:
a = np.array([[2, 5, 8], [-5, 7, 15], [10, 10.5, 6.2]])
a

array([[ 2. ,  5. ,  8. ],
       [-5. ,  7. , 15. ],
       [10. , 10.5,  6.2]])

In [ ]:
print("Mean =", a.mean())

Mean = 6.522222222222222


In [ ]:
print("Min =", a.min())

Min = -5.0


In [ ]:
print("Max =", a.max())

Max = 15.0


Phương thức **prod()** trả về tích của mảng các phần tử trên một trục nhất định. Theo mặc định, trục được đặt thành Không, do đó tính toán tích của tất cả các phần tử trong mảng đã cho

In [ ]:
print("Prod =", a.prod())

Prod = -27342000.0


Phương thức **std()**, được sử dụng để tính độ lệch chuẩn dọc theo trục được chỉ định. Hàm này trả về độ lệch chuẩn của các phần tử mảng. 

In [ ]:
print("Std =", a.std())

Std = 5.352419552102432


Theo mặc định, hàm **var()** tính toán phương sai tổng thể

In [ ]:
print("Var =", a.var())

Var = 28.648395061728397


Các hàm này chấp nhận một trục đối số tùy chọn cho phép thao tác được thực hiện trên các phần tử dọc theo trục đã cho

* Ví dụ: Hàm **sum()**

In [ ]:
b = np.arange(30).reshape(2, 3, 5)
b

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

**axis = 0**: Tổng các ma trận

In [ ]:
b.sum(axis = 0)

array([[15, 17, 19, 21, 23],
       [25, 27, 29, 31, 33],
       [35, 37, 39, 41, 43]])

**axis = 1**: Tổng mỗi cột của mỗi ma trận tạo thành 1 **element**, mỗi ma trận là 1 **array**

In [ ]:
b.sum(axis = 1)

array([[15, 18, 21, 24, 27],
       [60, 63, 66, 69, 72]])

**axis = 2**: Tổng mỗi dòng của mỗi ma trận tạo thành 1 **element**, mỗi ma trận là 1 **array**

In [ ]:
b.sum(axis = 2)

array([[ 10,  35,  60],
       [ 85, 110, 135]])

### **Universal functions**
**Universal functions** là các trình bao bọc được vectơ hóa các chức năng đơn giản

In [ ]:
c = np.random.randn(2, 3, 4)
c

array([[[-0.49358461, -0.23198114, -0.61840824, -0.6936827 ],
        [-2.19818317,  0.38997415, -0.51799017, -0.14951007],
        [ 0.4963275 ,  1.0623876 , -0.1086338 ,  0.14955787]],

       [[-0.19891246,  1.30657394,  0.31915632,  0.08771255],
        [ 1.13205311,  0.1122784 ,  0.20774334,  1.63014058],
        [ 1.3557875 ,  0.93364266, -0.13964975,  0.36114688]]])

**abs()**: Trả về mảng cùng kích thước với ***trị tuyệt đối*** các phần tử

In [ ]:
np.abs(c)

array([[[0.49358461, 0.23198114, 0.61840824, 0.6936827 ],
        [2.19818317, 0.38997415, 0.51799017, 0.14951007],
        [0.4963275 , 1.0623876 , 0.1086338 , 0.14955787]],

       [[0.19891246, 1.30657394, 0.31915632, 0.08771255],
        [1.13205311, 0.1122784 , 0.20774334, 1.63014058],
        [1.3557875 , 0.93364266, 0.13964975, 0.36114688]]])

**sqrt()**: Trả về mảng cùng kích thước với ***căn bậc 2*** các phần tử

In [ ]:
np.sqrt(c)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[[       nan,        nan,        nan,        nan],
        [       nan, 0.6244791 ,        nan,        nan],
        [0.70450515, 1.03072188,        nan, 0.38672713]],

       [[       nan, 1.14305465, 0.56493921, 0.29616304],
        [1.06397985, 0.33507969, 0.4557887 , 1.27676959],
        [1.16438288, 0.96625186,        nan, 0.60095498]]])

**log()**: Trả về mảng cùng kích thước với ***logarit cơ số e (logarit tự nhiên)*** các phần tử

In [ ]:
np.log(c)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.


array([[[        nan,         nan,         nan,         nan],
        [        nan, -0.94167482,         nan,         nan],
        [-0.70051929,  0.06051883,         nan, -1.90007185]],

       [[        nan,  0.2674084 , -1.14207428, -2.4336903 ],
        [ 0.1240329 , -2.18677377, -1.57145189,  0.48866626],
        [ 0.30438247, -0.06866151,         nan, -1.01847052]]])

**exp()**: Trả về mảng cùng kích thước với ***e mũ các phần tử***

In [ ]:
np.exp(c)

array([[[0.6104343 , 0.79296108, 0.5388014 , 0.49973231],
        [0.11100465, 1.47694262, 0.59571664, 0.86112976],
        [1.64267745, 2.89327072, 0.89705886, 1.16132068]],

       [[0.81962164, 3.69349787, 1.37596639, 1.09167427],
        [3.10201876, 1.1188243 , 1.23089721, 5.10459228],
        [3.8798151 , 2.54375836, 0.86966278, 1.43497422]]])

**sign()**: Trả về mảng đánh dấu cùng kích thước với

* Phần tử dương trả về 1
* Phần tử âm trả về -1
* Phần tử 0 trả về 0


In [ ]:
np.sign(c)

array([[[-1., -1., -1., -1.],
        [-1.,  1., -1., -1.],
        [ 1.,  1., -1.,  1.]],

       [[-1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.],
        [ 1.,  1., -1.,  1.]]])

**ceil()**: Trả về mảng toàn giá trị nguyên với phần tử là ***phần tử nhỏ nhất lớn hơn hoặc bằng*** phần tử mảng ban đầu

In [ ]:
np.ceil(c)

array([[[-0., -0., -0., -0.],
        [-2.,  1., -0., -0.],
        [ 1.,  2., -0.,  1.]],

       [[-0.,  2.,  1.,  1.],
        [ 2.,  1.,  1.,  2.],
        [ 2.,  1., -0.,  1.]]])

**modf()**: ***Tách phần nguyên và phần thập phân riêng lẻ***, mỗi phần là một **array** cùng kích thước

In [ ]:
np.modf(c)

(array([[[-0.49358461, -0.23198114, -0.61840824, -0.6936827 ],
         [-0.19818317,  0.38997415, -0.51799017, -0.14951007],
         [ 0.4963275 ,  0.0623876 , -0.1086338 ,  0.14955787]],
 
        [[-0.19891246,  0.30657394,  0.31915632,  0.08771255],
         [ 0.13205311,  0.1122784 ,  0.20774334,  0.63014058],
         [ 0.3557875 ,  0.93364266, -0.13964975,  0.36114688]]]),
 array([[[-0., -0., -0., -0.],
         [-2.,  0., -0., -0.],
         [ 0.,  1., -0.,  0.]],
 
        [[-0.,  1.,  0.,  0.],
         [ 1.,  0.,  0.,  1.],
         [ 1.,  0., -0.,  0.]]]))

**isnan()**: Kiểm tra mảng có phần tử NaN hay không

In [ ]:
np.isnan(c)

array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]])

**sin()**: Tính **sin** các phần tử trong mảng, tương tự với **cos**, **tan**, **arctan**

In [ ]:
print("sin =\n", np.sin(c))
print("cos =\n", np.cos(c))
print("tan =\n", np.tan(c))
print("cotan =\n", np.arctan(c))

sin =
 [[[-0.47378568 -0.22990604 -0.57973892 -0.63937313]
  [-0.80956428  0.38016451 -0.49513496 -0.14895369]
  [ 0.47619939  0.87352023 -0.10842026  0.14900096]]

 [[-0.19760335  0.96529587  0.31376559  0.08760012]
  [ 0.90528626  0.11204264  0.20625229  0.99823965]
  [ 0.97697451  0.80379232 -0.13919629  0.35334737]]]
cos =
 [[[ 0.88064018  0.97321283  0.81480229  0.76889661]
  [-0.58703124  0.92491889  0.86881607  0.98884417]
  [ 0.87933733  0.48678785  0.99410515  0.98883705]]

 [[ 0.98028206  0.26115872  0.94950048  0.99615572]
  [ 0.42480205  0.9937034   0.97849885 -0.05930943]
  [ 0.21335605  0.59491     0.99026481  0.93549219]]]
tan =
 [[[ -0.53800143  -0.23623409  -0.7115087   -0.8315463 ]
  [  1.37908209   0.4110247   -0.56989618  -0.15063414]
  [  0.54154347   1.79445773  -0.10906317   0.15068302]]

 [[ -0.20157805   3.69620388   0.33045333   0.08793818]
  [  2.13107791   0.1127526    0.2107844  -16.83104459]
  [  4.57908036   1.35111584  -0.14056471   0.37771279]]]
cotan =

### **Binary ufuncs**
Có nhiều hàm nhị phân, áp dụng theo từng phần tử trên hai **ndarrays**. Quy tắc **Broadcasting** được áp dụng nếu các mảng không có cùng hình dạng

In [ ]:
arr1 = np.array([1, -5, 7, -9])
arr2 = np.array([1.5, -2, -7. , 11])

**add(arr1, arr2)**: Tương đương với việc cộng hai mảng lại với nhau

In [ ]:
np.add(arr1, arr2)

array([ 2.5, -7. ,  0. ,  2. ])

**greater(arr1, arr2)**: So sánh các phần tử mảng **arr1** với các phần tử tương ứng mảng **arr2**, lớn hơn trả về **true** và ngược lại trả về **false**

In [ ]:
np.greater(arr1, arr2)

array([False, False,  True, False])

**maximum(arr1, arr2)**: Trả về **phần tử lớn nhất** giữa 2 phần tử tương ứng trong 2 mảng

In [ ]:
np.maximum(arr1, arr2)

array([ 1.5, -2. ,  7. , 11. ])

**copysign(arr1, arr2)**: Giữ nguyên giá trị và đổi dấu phần tử mảng arr1 theo mảng arr2

In [ ]:
np.copysign(arr2, arr1)

array([  1.5,  -2. ,   7. , -11. ])