![alt tag](https://codelearn.io/Upload/Blog/thu-vien-numpy-trong-python-63724882299.0039.png)

# **What is Numpy?**
**NumPy** là thư viện cơ bản cho tính toán khoa học bằng Python. Nó là một thư viện Python cung cấp một đối tượng mảng đa chiều, các đối tượng dẫn xuất khác nhau (chẳng hạn như các mảng và ma trận có mặt nạ) và một loạt các quy trình cho các hoạt động nhanh trên mảng, bao gồm toán học, logic, thao tác hình dạng, sắp xếp, lựa chọn, I / O , các phép biến đổi Fourier rời rạc, đại số tuyến tính cơ bản, các phép toán thống kê cơ bản, mô phỏng ngẫu nhiên và hơn thế nữa.

# **Reference**
https://github.com/ageron/handson-ml2/blob/ce94de16f017f78b0991a3d3ae18b3de70b15118/tools_numpy.ipynb

# **Numpy: Import**
Import thư viện **numpy**. Hầu hết mọi người sử dụng nó dưới dạng **np**

In [129]:
import numpy as np

# **Array indexing**


### **One-dimensional arrays**

In [130]:
a = np.array([5, -2, 5, 6, 8, 11, 3, 2, 13])
a

array([ 5, -2,  5,  6,  8, 11,  3,  2, 13])

**Truy cập 1 phần tử**

In [131]:
print("a[3] =", a[3])
print("a[7] =", a[7])

a[3] = 6
a[7] = 2


**Lấy tất cả phần tử**

In [132]:
a[:]

array([ 5, -2,  5,  6,  8, 11,  3,  2, 13])

**Truy cập các phần tử liên tiếp trong đoạn**

In [133]:
a[3:6] # a[3] a[4] a[5]

array([ 6,  8, 11])

In [134]:
a[:5] # Từ đầu tới a[4]

array([ 5, -2,  5,  6,  8])

In [135]:
a[3:] # a[3] đến phần tử cuối cùng

array([ 6,  8, 11,  3,  2, 13])

In [136]:
a[3: -1] # a[3] đến phần tử kế cuối

array([ 6,  8, 11,  3,  2])

**Truy cập phần tử theo** **step**

In [137]:
a[1::2] # a[1] với step bằng 2

array([-2,  6, 11,  2])

**Đảo mảng**

In [138]:
a[::-1]

array([13,  2,  3, 11,  8,  6,  5, -2,  5])

**Chỉnh sửa phần tử trong mảng**

In [139]:
a[5] = -999
a

array([   5,   -2,    5,    6,    8, -999,    3,    2,   13])

In [140]:
a[3: 7] = [0, 0, 0, 0]
a

array([ 5, -2,  5,  0,  0,  0,  0,  2, 13])

* Chỉnh sửa dựa vào quy tắc **Broadcasting**

In [141]:
a[3: 7] = 1
a

array([ 5, -2,  5,  1,  1,  1,  1,  2, 13])

* Nếu tạo một **array** mới từ 1 đoạn của **array** cũ và sửa đổi nó, điều này cũng sẽ sửa đổi **ndarray** ban đầu, và ngược lại

In [142]:
ab = a[3:7]
ab

array([1, 1, 1, 1])

In [143]:
ab[2] = 3
a

array([ 5, -2,  5,  1,  1,  3,  1,  2, 13])

In [144]:
a[4] = -1
ab

array([ 1, -1,  3,  1])

* Để chỉnh sửa dữ liệu không ảnh hưởng đến **array** khác, sử dụng phương thức **copy()**

In [145]:
acop = a[2: 7].copy()
acop

array([ 5,  1, -1,  3,  1])

In [146]:
a

array([ 5, -2,  5,  1, -1,  3,  1,  2, 13])

In [147]:
acop[2] = -100
acop

array([   5,    1, -100,    3,    1])

In [148]:
a

array([ 5, -2,  5,  1, -1,  3,  1,  2, 13])

### **Multi-dimensional arrays**
Các mảng đa chiều có thể được truy cập theo cách tương tự bằng cách cung cấp chỉ mục cho mỗi trục, được phân tách bằng dấu phẩy

In [149]:
b = np.arange(60).reshape(6, 10)
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [150]:
b[5, 7] # Dòng 5 cột 7

57

In [151]:
b[2, :] # Dòng 2 tất cả các cột

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [152]:
b[:, 3] # Cột 3 tất cả các dòng

array([ 3, 13, 23, 33, 43, 53])

Lưu ý 2 trường hợp

In [153]:
#th1
b[1, :]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [154]:
#th2
b[1:2, :]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

* Biểu thức đầu tiên trả về hàng 1 dưới dạng mảng 1D (12,)
* Biểu thức thứ hai trả về hàng 1 dưới dạng mảng 2D (1, 12)

### **Fancy index**

Chỉ định các cột (dòng) lấy ra

In [155]:
b[(0, 3), 3: 7]
# Dòng 0 & 3
# Cột 3 4 5 6

array([[ 3,  4,  5,  6],
       [33, 34, 35, 36]])

In [156]:
b[(0, 3, 2), (4, 8, 2)]
# b[0, 4]
# b[3, 8]
# b[2, 2]

array([ 4, 38, 22])

### **Higher dimensions**


In [157]:
c = np.arange(40).reshape(4, 2, 5)
c

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]]])

In [158]:
c[3, 1, 2]
# Ma trận 3
# Dòng 1
# Cột 2

37

In [159]:
c[3, :, 2]
# Ma trận 3
# Tất cả dòng
# Cột 2

array([32, 37])

Nếu không ghi một số **trục**, nó mặc định lấy tất cả

In [160]:
c[3, 1] # == c[3, 1, :]

array([35, 36, 37, 38, 39])

### **Ellipsis** (...)

In [161]:
d = np.arange(100).reshape(4, 5, 5)
d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74]],

       [[75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

In [162]:
d[2, ...]
# Ma trận 2
# Tất cả dòng
# Tất cả cột

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

### **Boolean indexing**

Sử dụng **Boolean array** để chỉ định các trục cần truy xuất

In [163]:
arr = np.arange(60).reshape(6, 10)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [164]:
arr_bool_r = np.array([True, False, True] * 2)

In [165]:
arr[arr_bool_r, :] # Dòng 0 2 3 5

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [166]:
arr_bool_c = np.array([False, False, False, False, False, True, False, True, True, False])

In [167]:
arr[:, arr_bool_c] # Cột 5 7 8

array([[ 5,  7,  8],
       [15, 17, 18],
       [25, 27, 28],
       [35, 37, 38],
       [45, 47, 48],
       [55, 57, 58]])

Truy xuất điều kiện

In [168]:
arr[arr % 5 == 3]

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58])

### **np.ix_**

In [169]:
arr[np.ix_(arr_bool_r, arr_bool_c)]

array([[ 5,  7,  8],
       [25, 27, 28],
       [35, 37, 38],
       [55, 57, 58]])