![alt tag](https://codelearn.io/Upload/Blog/thu-vien-numpy-trong-python-63724882299.0039.png)

# **What is Numpy?**
**NumPy** là thư viện cơ bản cho tính toán khoa học bằng Python. Nó là một thư viện Python cung cấp một đối tượng mảng đa chiều, các đối tượng dẫn xuất khác nhau (chẳng hạn như các mảng và ma trận có mặt nạ) và một loạt các quy trình cho các hoạt động nhanh trên mảng, bao gồm toán học, logic, thao tác hình dạng, sắp xếp, lựa chọn, I / O , các phép biến đổi Fourier rời rạc, đại số tuyến tính cơ bản, các phép toán thống kê cơ bản, mô phỏng ngẫu nhiên và hơn thế nữa.

# **Reference**
https://github.com/ageron/handson-ml2/blob/ce94de16f017f78b0991a3d3ae18b3de70b15118/tools_numpy.ipynb

# **Numpy: Import**
Import thư viện **numpy**. Hầu hết mọi người sử dụng nó dưới dạng **np**

In [23]:
import numpy as np

# **Iterating**

Lặp lại trên **ndarrays** rất giống với việc lặp qua các mảng python thông thường

In [24]:
arr = np.arange(60).reshape(3, 4, 5)
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

**Việc lặp qua các mảng nhiều chiều được thực hiện đối với trục đầu tiên**

In [25]:
for i in arr:
    print("item:\n", i)

item:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
item:
 [[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
item:
 [[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


In [26]:
for i in range(len(arr)):
    print("item: \n", arr[i])

item: 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
item: 
 [[20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]]
item: 
 [[40 41 42 43 44]
 [45 46 47 48 49]
 [50 51 52 53 54]
 [55 56 57 58 59]]


Lặp lại trên tất cả các phần tử trong **ndarray**, chỉ cần lặp qua thuộc tính **flat**

In [27]:
c = 1
for i in arr.flat:
    print("item", c, ": ", i)
    c += 1

item 1 :  0
item 2 :  1
item 3 :  2
item 4 :  3
item 5 :  4
item 6 :  5
item 7 :  6
item 8 :  7
item 9 :  8
item 10 :  9
item 11 :  10
item 12 :  11
item 13 :  12
item 14 :  13
item 15 :  14
item 16 :  15
item 17 :  16
item 18 :  17
item 19 :  18
item 20 :  19
item 21 :  20
item 22 :  21
item 23 :  22
item 24 :  23
item 25 :  24
item 26 :  25
item 27 :  26
item 28 :  27
item 29 :  28
item 30 :  29
item 31 :  30
item 32 :  31
item 33 :  32
item 34 :  33
item 35 :  34
item 36 :  35
item 37 :  36
item 38 :  37
item 39 :  38
item 40 :  39
item 41 :  40
item 42 :  41
item 43 :  42
item 44 :  43
item 45 :  44
item 46 :  45
item 47 :  46
item 48 :  47
item 49 :  48
item 50 :  49
item 51 :  50
item 52 :  51
item 53 :  52
item 54 :  53
item 55 :  54
item 56 :  55
item 57 :  56
item 58 :  57
item 59 :  58
item 60 :  59
