![alt tag](https://codelearn.io/Upload/Blog/thu-vien-numpy-trong-python-63724882299.0039.png)

# **What is Numpy?**
**NumPy** là thư viện cơ bản cho tính toán khoa học bằng Python. Nó là một thư viện Python cung cấp một đối tượng mảng đa chiều, các đối tượng dẫn xuất khác nhau (chẳng hạn như các mảng và ma trận có mặt nạ) và một loạt các quy trình cho các hoạt động nhanh trên mảng, bao gồm toán học, logic, thao tác hình dạng, sắp xếp, lựa chọn, I / O , các phép biến đổi Fourier rời rạc, đại số tuyến tính cơ bản, các phép toán thống kê cơ bản, mô phỏng ngẫu nhiên và hơn thế nữa.

# **Reference**
https://github.com/ageron/handson-ml2/blob/ce94de16f017f78b0991a3d3ae18b3de70b15118/tools_numpy.ipynb

# **Numpy: Import**
Import thư viện **numpy**. Hầu hết mọi người sử dụng nó dưới dạng **np**

In [45]:
import numpy as np

# **Stacking arrays**
Điều này thường có ích khi xếp chồng các mảng khác nhau lại với nhau

In [46]:
arr1 = np.ones((3, 4))
arr2 = np.full((4, 4), 2.0)
arr3 = np.full((3, 4), 3.0)

In [47]:
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [48]:
arr2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [49]:
arr3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

### **vstack**
Chồng các **arrays** lên với nhau, tất nhiên các **arrays** phải cùng chỉ số **column**

In [50]:
arr4 = np.vstack((arr1, arr2, arr3))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [51]:
arr4.shape

(10, 4)

### **hstack**
Sắp các **arrays** ngang hàng với nhau, tất nhiên các **arrays** phải cùng chỉ số **row**

In [52]:
arr5 = np.hstack((arr1, arr3))
arr5

array([[1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.]])

In [53]:
arr5.shape

(3, 8)

### **concatenate**
Nối các **arrays** với nhau theo bất kì trục nào dựa vào thuộc tính **axis**
* axis = 0: Chồng các array lên nhau (theo cột)
* axis = 1: Nối các array với nhau hàng ngang (theo dòng)

In [55]:
arr6 = np.concatenate((arr1, arr2, arr3), axis = 0) # Tương tự như vstack
arr6

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [57]:
arr7 = np.concatenate((arr1, arr3), axis = 1) # Tương tự như hstack
arr7

array([[1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.],
       [1., 1., 1., 1., 3., 3., 3., 3.]])

### **stack**
Hàm **stack** sắp xếp các **arrays** dọc theo một trục mới. Tất cả các **arrays** phải có cùng hình dạng

In [59]:
arr8 = np.stack((arr1, arr3))
arr8

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]])

In [60]:
arr8.shape

(2, 3, 4)