![alt tag](https://codelearn.io/Upload/Blog/thu-vien-numpy-trong-python-63724882299.0039.png)

# **What is Numpy?**
**NumPy** là thư viện cơ bản cho tính toán khoa học bằng Python. Nó là một thư viện Python cung cấp một đối tượng mảng đa chiều, các đối tượng dẫn xuất khác nhau (chẳng hạn như các mảng và ma trận có mặt nạ) và một loạt các quy trình cho các hoạt động nhanh trên mảng, bao gồm toán học, logic, thao tác hình dạng, sắp xếp, lựa chọn, I / O , các phép biến đổi Fourier rời rạc, đại số tuyến tính cơ bản, các phép toán thống kê cơ bản, mô phỏng ngẫu nhiên và hơn thế nữa.

# **Reference**
https://github.com/ageron/handson-ml2/blob/ce94de16f017f78b0991a3d3ae18b3de70b15118/tools_numpy.ipynb

# **Numpy: Import**
Import thư viện **numpy**. Hầu hết mọi người sử dụng nó dưới dạng **np**

In [19]:
import numpy as np

# **Splitting arrays**
Chia mảng ban đầu thành các mảng con

In [20]:
arr1 = np.arange(54).reshape(9, 6)
arr1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53]])

Chia thành các phần bằng nhau **theo chiều dọc**

Có 2 cách thực hiện:
1.   Dùng phương thức **vsplit**, tức là phân chia trực tiếp theo chiều dọc
2.   Dùng phương thức chung **split** và sử dụng thuộc tính **axis = 0**
**Lưu ý**: Số lượng dòng phải chia hết cho số lượng mảng con cần phân chia


In [21]:
arr2, arr3, arr4 = np.split(arr1, 3, axis = 0) # ~ np.vsplit(arr1, 3)

In [22]:
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [23]:
arr3

array([[18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [24]:
arr4

array([[36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53]])

Chia thành các phần bằng nhau **theo chiều ngang**

Có 2 cách thực hiện:
1.   Dùng phương thức **hsplit**, tức là phân chia trực tiếp theo chiều ngang
2.   Dùng phương thức chung **split** và sử dụng thuộc tính **axis = 1**
**Lưu ý**: Số lượng cột phải chia hết cho số lượng mảng con cần phân chia


In [25]:
arr5, arr6 = np.split(arr1, 2, axis = 1) # ~ np.hsplit(arr1, 2)

In [26]:
arr5

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14],
       [18, 19, 20],
       [24, 25, 26],
       [30, 31, 32],
       [36, 37, 38],
       [42, 43, 44],
       [48, 49, 50]])

In [27]:
arr6

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23],
       [27, 28, 29],
       [33, 34, 35],
       [39, 40, 41],
       [45, 46, 47],
       [51, 52, 53]])