![alt tag](https://codelearn.io/Upload/Blog/thu-vien-numpy-trong-python-63724882299.0039.png)

# **What is Numpy?**
**NumPy** là thư viện cơ bản cho tính toán khoa học bằng Python. Nó là một thư viện Python cung cấp một đối tượng mảng đa chiều, các đối tượng dẫn xuất khác nhau (chẳng hạn như các mảng và ma trận có mặt nạ) và một loạt các quy trình cho các hoạt động nhanh trên mảng, bao gồm toán học, logic, thao tác hình dạng, sắp xếp, lựa chọn, I / O , các phép biến đổi Fourier rời rạc, đại số tuyến tính cơ bản, các phép toán thống kê cơ bản, mô phỏng ngẫu nhiên và hơn thế nữa.

# **Reference**
https://github.com/ageron/handson-ml2/blob/ce94de16f017f78b0991a3d3ae18b3de70b15118/tools_numpy.ipynb

# **Numpy: Import**
Import thư viện **numpy**. Hầu hết mọi người sử dụng nó dưới dạng **np**

In [39]:
import numpy as np

# **Transposing arrays**
Phương thức **transpose** tạo ra một khung nhìn mới trên dữ liệu của **ndarray**, với các trục được hoán vị theo thứ tự đã cho

In [40]:
arr1 = np.arange(120).reshape(4, 5, 6)
arr1

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29]],

       [[ 30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89]],

       [[ 90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119]]])

Tạo một **ndarray** sao cho các trục mặc định 0, 1, 2 (chiều sâu, chiều cao, chiều rộng) được sắp xếp lại thành 1, 2, 0 (chiều sâu → chiều rộng, chiều cao → chiều sâu, chiều rộng → chiều cao)
    
    d h w
    h w d

In [41]:
arr2 = arr1.transpose((1, 2, 0))
arr2

array([[[  0,  30,  60,  90],
        [  1,  31,  61,  91],
        [  2,  32,  62,  92],
        [  3,  33,  63,  93],
        [  4,  34,  64,  94],
        [  5,  35,  65,  95]],

       [[  6,  36,  66,  96],
        [  7,  37,  67,  97],
        [  8,  38,  68,  98],
        [  9,  39,  69,  99],
        [ 10,  40,  70, 100],
        [ 11,  41,  71, 101]],

       [[ 12,  42,  72, 102],
        [ 13,  43,  73, 103],
        [ 14,  44,  74, 104],
        [ 15,  45,  75, 105],
        [ 16,  46,  76, 106],
        [ 17,  47,  77, 107]],

       [[ 18,  48,  78, 108],
        [ 19,  49,  79, 109],
        [ 20,  50,  80, 110],
        [ 21,  51,  81, 111],
        [ 22,  52,  82, 112],
        [ 23,  53,  83, 113]],

       [[ 24,  54,  84, 114],
        [ 25,  55,  85, 115],
        [ 26,  56,  86, 116],
        [ 27,  57,  87, 117],
        [ 28,  58,  88, 118],
        [ 29,  59,  89, 119]]])

In [42]:
arr2.shape

(5, 6, 4)

Phương thức **transpose** sẽ đảo ngược **shape** nếu không có đối số trong phương thức

In [43]:
arr3 = arr1.transpose()
arr3

array([[[  0,  30,  60,  90],
        [  6,  36,  66,  96],
        [ 12,  42,  72, 102],
        [ 18,  48,  78, 108],
        [ 24,  54,  84, 114]],

       [[  1,  31,  61,  91],
        [  7,  37,  67,  97],
        [ 13,  43,  73, 103],
        [ 19,  49,  79, 109],
        [ 25,  55,  85, 115]],

       [[  2,  32,  62,  92],
        [  8,  38,  68,  98],
        [ 14,  44,  74, 104],
        [ 20,  50,  80, 110],
        [ 26,  56,  86, 116]],

       [[  3,  33,  63,  93],
        [  9,  39,  69,  99],
        [ 15,  45,  75, 105],
        [ 21,  51,  81, 111],
        [ 27,  57,  87, 117]],

       [[  4,  34,  64,  94],
        [ 10,  40,  70, 100],
        [ 16,  46,  76, 106],
        [ 22,  52,  82, 112],
        [ 28,  58,  88, 118]],

       [[  5,  35,  65,  95],
        [ 11,  41,  71, 101],
        [ 17,  47,  77, 107],
        [ 23,  53,  83, 113],
        [ 29,  59,  89, 119]]])

In [44]:
arr3.shape

(6, 5, 4)

Sử dụng phương thức **swapaxes** để hoán đổi nhanh 2 trục

In [45]:
arr4 = arr1.swapaxes(1, 2) # ~ arr1.transpose((0, 2, 1))
arr4

array([[[  0,   6,  12,  18,  24],
        [  1,   7,  13,  19,  25],
        [  2,   8,  14,  20,  26],
        [  3,   9,  15,  21,  27],
        [  4,  10,  16,  22,  28],
        [  5,  11,  17,  23,  29]],

       [[ 30,  36,  42,  48,  54],
        [ 31,  37,  43,  49,  55],
        [ 32,  38,  44,  50,  56],
        [ 33,  39,  45,  51,  57],
        [ 34,  40,  46,  52,  58],
        [ 35,  41,  47,  53,  59]],

       [[ 60,  66,  72,  78,  84],
        [ 61,  67,  73,  79,  85],
        [ 62,  68,  74,  80,  86],
        [ 63,  69,  75,  81,  87],
        [ 64,  70,  76,  82,  88],
        [ 65,  71,  77,  83,  89]],

       [[ 90,  96, 102, 108, 114],
        [ 91,  97, 103, 109, 115],
        [ 92,  98, 104, 110, 116],
        [ 93,  99, 105, 111, 117],
        [ 94, 100, 106, 112, 118],
        [ 95, 101, 107, 113, 119]]])

In [46]:
arr4.shape

(4, 6, 5)