![alt tag](https://codelearn.io/Upload/Blog/thu-vien-numpy-trong-python-63724882299.0039.png)

# **What is Numpy?**
**NumPy** là thư viện cơ bản cho tính toán khoa học bằng Python. Nó là một thư viện Python cung cấp một đối tượng mảng đa chiều, các đối tượng dẫn xuất khác nhau (chẳng hạn như các mảng và ma trận có mặt nạ) và một loạt các quy trình cho các hoạt động nhanh trên mảng, bao gồm toán học, logic, thao tác hình dạng, sắp xếp, lựa chọn, I / O , các phép biến đổi Fourier rời rạc, đại số tuyến tính cơ bản, các phép toán thống kê cơ bản, mô phỏng ngẫu nhiên và hơn thế nữa.

# **Reference**
https://github.com/ageron/handson-ml2/blob/ce94de16f017f78b0991a3d3ae18b3de70b15118/tools_numpy.ipynb

# **Numpy: Import**
Import thư viện **numpy**. Hầu hết mọi người sử dụng nó dưới dạng **np**

In [32]:
import numpy as np

# **Linear Algebra**
Mảng 2D **NumPy** có thể được sử dụng để biểu diễn ma trận một cách hiệu quả trong python. Để hiểu được những vấn đề dưới đây, cần phải có kiến thức cơ bản về đại số tuyến tính, trong tài liệu dưới đây sẽ không giải thích về các khái niệm

### **Matrix transpose (Ma trận chuyển vị)**

In [33]:
m1 = np.arange(24).reshape(4, 6)
m1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [34]:
m1.T

array([[ 0,  6, 12, 18],
       [ 1,  7, 13, 19],
       [ 2,  8, 14, 20],
       [ 3,  9, 15, 21],
       [ 4, 10, 16, 22],
       [ 5, 11, 17, 23]])

In [35]:
m2 = np.array([1, 2, 3, 4, 5]).reshape(1, 5)
m2 

array([[1, 2, 3, 4, 5]])

In [36]:
m2.T

array([[1],
       [2],
       [3],
       [4],
       [5]])

### **Matrix multiplication (Phép nhân ma trận)**
Lưu ý:
1. Số cột của ma trận đứng trước phải bằng số dòng của ma trận đứng sau
2. Phép nhân ma trận không có tính giao hoán

In [37]:
ma1 = np.arange(24).reshape(4, 6)
ma1

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [38]:
ma2 = np.arange(12).reshape(6, 2)
ma2

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [39]:
ma1.dot(ma2)

array([[110, 125],
       [290, 341],
       [470, 557],
       [650, 773]])

### **Matrix inverse (Ma trận nghịch đảo)**

In [40]:
import numpy.linalg as linalg

In [41]:
ma3 = np.array([[1, 2, 3], [5, 7, 11], [21, 29, 31]])
ma3

array([[ 1,  2,  3],
       [ 5,  7, 11],
       [21, 29, 31]])

In [42]:
linalg.inv(ma3)

array([[-2.31818182,  0.56818182,  0.02272727],
       [ 1.72727273, -0.72727273,  0.09090909],
       [-0.04545455,  0.29545455, -0.06818182]])

### **Identity matrix (Ma trận đơn vị)**

Bản chất nó là tích của ma trận với ma trận nghịch đảo (với dấu phẩy động nhỏ, tức kết quả ko hoàn toàn là 1 số nguyên)

In [43]:
ma3.dot(linalg.inv(ma3))

array([[ 1.00000000e+00, -1.66533454e-16,  0.00000000e+00],
       [ 6.31439345e-16,  1.00000000e+00, -1.38777878e-16],
       [ 5.21110932e-15, -2.38697950e-15,  1.00000000e+00]])

Ma trận đơn vị khá đơn giản, có thể xem qua phương thức **eye**

In [44]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### **QR decomposition (Phân hủy QR)**
Đưa 1 ma trận về tích của 2 ma trận

In [45]:
q, r = linalg.qr(ma3)

In [46]:
q

array([[-0.04627448,  0.98786672,  0.14824986],
       [-0.23137241,  0.13377362, -0.96362411],
       [-0.97176411, -0.07889213,  0.22237479]])

In [47]:
r

array([[-21.61018278, -29.89331494, -32.80860727],
       [  0.        ,   0.62427688,   1.9894538 ],
       [  0.        ,   0.        ,  -3.26149699]])

In [48]:
q.dot(r) # q.r = ma3

array([[ 1.,  2.,  3.],
       [ 5.,  7., 11.],
       [21., 29., 31.]])

### **Determinant (Định thức của ma trận)**

In [49]:
ma3

array([[ 1,  2,  3],
       [ 5,  7, 11],
       [21, 29, 31]])

In [50]:
linalg.det(ma3)

43.99999999999997

### **Eigenvalues and eigenvectors (Giá trị riêng và vector riêng)**

In [51]:
eigenvalues, eigenvectors = linalg.eig(ma3)

In [52]:
eigenvalues # λ: Giá trị riêng của ma trận

array([42.26600592, -0.35798416, -2.90802176])

In [53]:
eigenvectors # x: vector riêng của ma trận

array([[-0.08381182, -0.76283526, -0.18913107],
       [-0.3075286 ,  0.64133975, -0.6853186 ],
       [-0.94784057, -0.08225377,  0.70325518]])

In [54]:
ma3.dot(eigenvectors) - eigenvalues * eigenvectors  # ma3.x - λ*x = 0

array([[ 8.88178420e-15,  2.22044605e-16, -3.10862447e-15],
       [ 3.55271368e-15,  2.02615702e-15, -1.11022302e-15],
       [ 3.55271368e-14,  3.33413852e-15, -8.43769499e-15]])

### **Diagonal (Đường chéo chính)**

In [55]:
ma3

array([[ 1,  2,  3],
       [ 5,  7, 11],
       [21, 29, 31]])

In [56]:
np.diag(ma3)

array([ 1,  7, 31])

### **Trace (Vết)**
Vết ma trận là tổng các phần tử trên đường chéo chính

In [57]:
ma3

array([[ 1,  2,  3],
       [ 5,  7, 11],
       [21, 29, 31]])

In [58]:
np.trace(ma3) # 1 + 7 + 31

39

### **Solving a system of linear scalar equations (Giải hệ phương trình tuyến tính vô hướng)**

Ví dụ mẫu phương trình:
    
* **$2x +6y + 8z = 54$**

* **$-2x -6y + 1 = 0$**

* **$-3x -3y +9z = 57$**

In [59]:
equa = np.array([[2, 6, 8], [-2, -6, 1], [-3, -3, 9]])
res = np.array([54, 0, 57])
sol = linalg.solve(equa, res)

In [60]:
sol

array([-3.,  2.,  6.])

**Kiểm tra kết quả theo 2 cách**

**Cách 1**: Thực hiện phép tính ngược

In [61]:
equa.dot(sol) # Kết quả trả về bằng res là True

array([54.,  0., 57.])

**Cách 2**: Để máy tính kiểm tra

In [62]:
np.allclose(equa.dot(sol), res)

True