In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


# **Library**

In [ ]:
import tensorflow as tf
import numpy as np

Tensors are multi-dimensional arrays with a uniform type (called a `dtype`)

If you're familiar with `NumPy`, tensor are (kind of) like `np.arrays`

All tensors are immutable like Python numbers and strings: You can never update the contents of a tensor, only create a new one

# **Basic**

Here is a "scalar" or "rank-0" tensor. A scalar contains a single value, and no "axes"

In [ ]:
rank_0_tensor = tf.constant(4)
rank_0_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=4>

A "vector" or "rank-1" tensor is like a list of values. A vector has one axis

In [ ]:
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


A "matrix" or "rank-2" tensor has two axis

In [ ]:
rank_2_tensor = tf.constant(
    [[1, 2],
     [3, 4],
     [5, 6]], dtype=tf.float16
)
rank_2_tensor

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

| A scalar, shape: [] | A vector, shape: [3] | A matrix, shape: [3, 2] |
|-------------------------|----------------------|---------------------|
|![](https://www.tensorflow.org/static/guide/images/tensor/scalar.png)|![](https://www.tensorflow.org/static/guide/images/tensor/vector.png)|![](https://www.tensorflow.org/static/guide/images/tensor/matrix.png)|

Tensors may have more axes; here is a tensor with three axes

In [ ]:
rank_3_tensor = tf.constant([
    [[0, 1, 2, 3, 4],
     [5, 6, 7, 8, 9]],
    [[10, 11, 12, 13, 14],
     [15, 16, 17, 18, 19]],
    [[20, 21, 22, 23, 24],
     [25, 26, 27, 28, 29]]
])
rank_3_tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]], dtype=int32)>

||A 3-axis tensor, shape: [3, 2, 5]||
|---|---|---|
|![](https://www.tensorflow.org/static/guide/images/tensor/3-axis_numpy.png)|![](https://www.tensorflow.org/static/guide/images/tensor/3-axis_front.png)|![](https://www.tensorflow.org/static/guide/images/tensor/3-axis_block.png)|

You can convert a tensor to a NumPy array either using `np.array` or `tensor.numpy` method:

In [ ]:
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

or

In [ ]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

Tensors often contain floats and ints, but have many other types, including:

* complex numbers
* strings

In [ ]:
tensor_a = tf.constant([
    [1, 2],
    [3, 4]
])

tensor_b = tf.ones([2, 2], dtype = tf.int32)

print(tf.add(tensor_a, tensor_b), "\n") # print(tensor_a + tensor_b)
print(tf.multiply(tensor_a, tensor_b), "\n") # print(tensor_a * tensor_b)
print(tf.matmul(tensor_a, tensor_b), "\n") # print(tensor_a @ tensor_b)

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [ ]:
print(tensor_a + tensor_b, "\n")
print(tensor_a * tensor_b, "\n")
print(tensor_a @ tensor_b, "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



Tensors are used in all kinds of operations (or "Ops")

In [ ]:
tensor_c = ([
    [4.0, 5.0],
    [10.0, 1.0]
])

In [ ]:
# Find the largest value
print(tf.reduce_max(tensor_c))

# Find the index of the largest value
print(tf.math.argmax(tensor_c))

# Compute the softmax
print(tf.nn.softmax(tensor_c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


In [ ]:
tf.convert_to_tensor([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
tf.reduce_max([1, 2, 3])

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
tf.reduce_max(np.array([1, 2, 3]))

<tf.Tensor: shape=(), dtype=int64, numpy=3>

# **About shapes**

Tensors have shapes. Some vocabulary:
* **Shape**: The length (number of elements) of each of the axes of a tensor.
* **Rank**: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix is rank 2.
* **Axis** or **Dimension**: A particular dimension of a tensor
* **Size**: The total number of items in the tensor, the product of the shape vector's elements

In [ ]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

|A rank-4 tensor, shape: [3, 2, 4, 5]||
|---|---|
|![](https://www.tensorflow.org/static/guide/images/tensor/shape.png)|![](https://www.tensorflow.org/static/guide/images/tensor/4-axis_block.png)|

In [ ]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of axes:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of axes: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


|Typical axis order|
|---|
|![](https://www.tensorflow.org/static/guide/images/tensor/shape2.png)|

# **Indexing**

## Single-axis index

TensorFlow follows standard Python indexing rules and the basic rules for NumPy indexing
* indexes start at `0`
* negative indices count backwards from the end
* colons, `:`, are used for slices: `start:stop:step`

In [ ]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 45])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34 45]


In [ ]:
for i in range(0, tf.size(rank_1_tensor).numpy()):
    print(f"Pos {i}:", rank_1_tensor[i].numpy())

Pos 0: 0
Pos 1: 1
Pos 2: 1
Pos 3: 2
Pos 4: 3
Pos 5: 5
Pos 6: 8
Pos 7: 13
Pos 8: 21
Pos 9: 34
Pos 10: 45


In [ ]:
# [start:stop:step]
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34 45]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34 45]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21 45]
Reversed: [45 34 21 13  8  5  3  2  1  1  0]


## Multi-axis index

In [ ]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [ ]:
rank_2_tensor[1,1].numpy()

4.0

In [ ]:
print("Second row:", rank_2_tensor[1,:].numpy())
print("Second column:", rank_2_tensor[:,1].numpy())
print("Last row:", rank_2_tensor[-1,:].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:\n", rank_2_tensor[1:, :].numpy())

Second row: [3. 4.]
Second column: [2. 4. 6.]
Last row: [5. 6.]
First item in last column: 2.0
Skip the first row:
 [[3. 4.]
 [5. 6.]]


In [ ]:
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [ ]:
rank_3_tensor[:, :, 4].numpy()

array([[ 4,  9],
       [14, 19],
       [24, 29]], dtype=int32)

|Selecting the last feature across all locations in each example in the batch|
|---|
|![](https://www.tensorflow.org/static/guide/images/tensor/index1.png)|

# **Manipulating Shapes**

Reshaping a tensor is of great utility

In [ ]:
tensor_x = tf.constant([[1], [2], [3]])
print("Tensor:", tensor_x)
print("Shape:", tensor_x.shape)

Tensor: tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32)
Shape: (3, 1)


In [ ]:
# You can convert this object into a Python list, too
tensor_x.shape.as_list()

[3, 1]

In [ ]:
reshaped = tf.reshape(tensor_x, [1, 3])
print(tensor_x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


In [ ]:
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


If you flatten a tensor you can see what order it is laid out in memory.

In [ ]:
print(tf.reshape(rank_3_tensor, [-1]))

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


In [ ]:
print(tf.reshape(rank_3_tensor, [3*2, 5]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32)


In [ ]:
print(tf.reshape(rank_3_tensor, [3, -1])) # -1 in order to flatten

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


||Some good reshapes.||
|-|-|-|
|![](https://www.tensorflow.org/static/guide/images/tensor/reshape-before.png)|![](https://www.tensorflow.org/static/guide/images/tensor/reshape-good1.png)|![](https://www.tensorflow.org/static/guide/images/tensor/reshape-good2.png)|

In [ ]:
# You can't reorder axes with reshape.
print(tf.reshape(rank_3_tensor, [2, 3, 5]), "\n") 

# This is a mess
print(tf.reshape(rank_3_tensor, [5, 6]), "\n")

# This doesn't work at all
try:
  tf.reshape(rank_3_tensor, [7, -1])
except Exception as e:
  print(f"{type(e).__name__}: {e}")

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]], shape=(2, 3, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]], shape=(5, 6), dtype=int32) 

InvalidArgumentError: Input to reshape is a tensor with 30 values, but the requested shape requires a multiple of 7 [Op:Reshape]


||Some bad reshapes.||
|-|-|-|
|![](https://www.tensorflow.org/static/guide/images/tensor/reshape-bad.png)|![](https://www.tensorflow.org/static/guide/images/tensor/reshape-bad4.png)|![](https://www.tensorflow.org/static/guide/images/tensor/reshape-bad2.png)|

# **More on DTypes**

To inspect `tf.Tensor`'s data type use the `Tensor.dtype` property

TensorFlow converts Python integers to `tf.int32` and Python floating point numbers to `tf.float32`

Yoy can cast from type to type

In [ ]:
the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)
the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)
# Now, cast to an uint8 and lose the decimal precision
the_u8_tensor = tf.cast(the_f64_tensor, dtype=tf.uint8)
the_u8_tensor

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([2, 3, 4], dtype=uint8)>

# **Broadcasting**

The simplest and most common case in when you attempt to multiply or add a tensor to a scalar. In that case, the scalar is broadcast to be the same shape as the other argument

In [ ]:
tensor_x = tf.constant([1, 2, 3])
tensor_y = tf.constant(2)
tensor_z = tf.constant([2, 2, 2])

In [39]:
# All of these are the same computation
print(tf.multiply(tensor_x, 2)) # [1, 2, 3] * 2
print(tensor_x * tensor_y) # [1, 2, 3] * (2)
print(tensor_x * tensor_z) # [1, 2, 3] * [2, 2, 2]

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


Likewise, axes with length 1 can be stretched out to match the other arguments. Both arguments can be stretched in the same computation.

In [44]:
tensor_x = tf.reshape(tensor_x, [3, 1])
tensor_y = tf.range(1, 5)

In [45]:
print(tensor_x, "\n")
print(tensor_y, "\n")
print(tf.multiply(tensor_x, tensor_y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


|A broadcasted add: a [3, 1] times a [1, 4] gives a [3,4]|
|-|
|![](https://www.tensorflow.org/static/guide/images/tensor/broadcasting.png)|

Here is the same operation without broadcasting:

In [47]:
x_stretch = tf.constant([
    [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 1],
])
y_stretch = tf.constant([
    [1, 2, 3, 4],
    [1, 2, 3, 4],
    [1, 2, 3, 4]
])
x_stretch * y_stretch

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 2, 3, 4],
       [2, 4, 6, 8],
       [3, 6, 9, 4]], dtype=int32)>

You see what broadcasting looks like using `tf.broadcast_to`

In [51]:
print(tf.broadcast_to(tf.constant([1, 2, 3, 4]), [6, 4]))

tf.Tensor(
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]], shape=(6, 4), dtype=int32)


# **Ragged Tensors**

A tensor with variable numbers of elements along some axis is called "ragged". Use `tf.ragged.RaggedTensor` for ragged data

|A tf.RaggedTensor, shape: [4, None]|
|-|
|![](https://www.tensorflow.org/static/guide/images/tensor/ragged.png)|

In [52]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]
]

In [54]:
try:
    tensor = tf.constant(ragged_list)
except Exception as e:
    print(f"{type(e) .__name__}: {e}")

ValueError: Can't convert non-rectangular Python sequence to Tensor.


Instead create a `tf.RaggedTensor` using `tf.ragged.constant`

In [56]:
ragged_tensor = tf.ragged.constant(ragged_list)
ragged_tensor

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>

In [57]:
ragged_tensor.shape

TensorShape([4, None])

# **String tensors**

`tf.string` is a `dtype`, which is to say you can represent data as strings (variable-length byte arrays) in tensors

Here is a scalar string tensor:

In [59]:
# Tensors can be strings, too here is a scalar string
scalar_string_tensor = tf.constant("Gray wolf")
scalar_string_tensor

<tf.Tensor: shape=(), dtype=string, numpy=b'Gray wolf'>

And vector of strings:

|A vector of strings, shape: [3,]|
|-|
|![](https://www.tensorflow.org/static/guide/images/tensor/strings.png)|

In [61]:
# If you have three string tensors of different lengths, this is OK.
tensor_of_strings = tf.constant([
    "Gray wolf",
    "Quick brown fox",
    "Lazy dog"
])

# Note that the shape is (3,). The string length is not included.
print(tensor_of_strings)

tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)


Some basic functions with strings can be found in `tf.strings`, including `tf.strings.split.`

In [62]:
# You can use split to split a string into a set of tensors
print(tf.strings.split(scalar_string_tensor, sep=" "))

tf.Tensor([b'Gray' b'wolf'], shape=(2,), dtype=string)


In [63]:
print(tf.strings.split(tensor_of_strings))

<tf.RaggedTensor [[b'Gray', b'wolf'], [b'Quick', b'brown', b'fox'], [b'Lazy', b'dog']]>


|Three strings split, shape: [3, None]|
|-|
|![](https://www.tensorflow.org/static/guide/images/tensor/string-split.png)|

And `tf.string.to_number`:

In [65]:
text = tf.constant("1 10 100")
print(tf.strings.to_number(tf.strings.split(text, " ")))

tf.Tensor([  1.  10. 100.], shape=(3,), dtype=float32)


# **Sparse tensors**

Sometimes, your data is sparse, like a very wide embedding space. TensorFlow supports `tf.sparse.SparseTensor` and related operations to store sparse data efficiently.

|A tf.SparseTensor, shape: [3, 4]|
|-|
|![](https://www.tensorflow.org/static/guide/images/tensor/sparse.png)|

In [69]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(
    indices=[[0, 1], [1, 2]],
    values=[1, 2],
    dense_shape=[3, 4]
)
print(sparse_tensor, "\n")

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 



In [70]:
# You can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

tf.Tensor(
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
